# Flathead Robot Head - Fusion 360 Design

## Quick Start

### Установка скрипта в Fusion 360

1. Открой Fusion 360
2. Меню: **Tools → Add-Ins → Scripts and Add-Ins** (или нажми `Shift+S`)
3. Вкладка **Scripts** → нажми **+** (Create)
4. Выбери папку и имя (например `FlatheadHead`)
5. Скопируй содержимое `fusion_head_design.py` в открывшийся файл
6. Нажми **Run**

### Что получишь

Параметрическая модель головы робота с:

```
┌─────────────────────────────────────┐
│           ROBOT HEAD                │
│                                     │
│  [CAM L]              [CAM R]       │  ← 2x Pi Camera v3 (stereo 70mm)
│     ●                    ●          │
│                                     │
│  [MIC]                  [MIC]       │  ← 4x INMP441 микрофона
│                                     │
│           (  O  )                   │  ← Speaker 40mm
│                                     │
│  [MIC]                  [MIC]       │
│                                     │
│  ┌─────────────────────────────┐    │
│  │  ESP32      │   PAM8403     │    │  ← Электроника
│  └─────────────────────────────┘    │
│                                     │
└──────────────┬──────────────────────┘
               │
          [PAN SERVO]                    ← MG996R горизонтальный поворот
               │
         [TILT SERVO]                    ← MG996R наклон
               │
            (neck)
```

## Размеры компонентов (встроены в скрипт)

| Компонент | Размеры (мм) | Крепёж |
|-----------|--------------|--------|
| Pi Camera v3 | 25 x 24 x 9 | M2 (21 x 12.5mm) |
| INMP441 | 14 x 10 x 3.5 | - |
| Speaker 40mm | Ø40 x 15 | M3 (34mm) |
| PAM8403 | 30 x 20 x 10 | - |
| ESP32 DevKit | 55 x 28 x 10 | M3 (48 x 23mm) |
| MG996R | 40.7 x 19.7 x 42.9 | M3 (49.5mm tabs) |

## Параметры (можно менять в Fusion)

После запуска скрипта, в панели **Parameters** (`Modify → Change Parameters`):

- `HeadWidth` - ширина головы (по умолчанию 120mm)
- `HeadHeight` - высота головы (100mm)
- `HeadDepth` - глубина (80mm)
- `StereoBaseline` - расстояние между камерами (70mm)
- `WallThickness` - толщина стенок (3mm)

## Структура компонентов

```
Flathead_Robot_Head
├── Head_Shell          ← Основной корпус
├── Camera_Mounts       ← Крепления камер
│   ├── Camera_Bracket_L
│   └── Camera_Bracket_R
├── Microphone_Mounts   ← Крепления микрофонов
│   ├── Mic_Post_FL
│   ├── Mic_Post_FR
│   ├── Mic_Post_BL
│   └── Mic_Post_BR
├── Speaker_Mount       ← Крепление динамика
├── Electronics_Bay     ← Отсек электроники
│   ├── ESP32_Tray
│   └── Amplifier_Tray
└── Pan_Tilt_Mechanism  ← Механизм поворота
    ├── Pan_Servo_Bracket
    ├── Tilt_Servo_Bracket
    └── Neck_Tube
```

## Экспорт для печати

1. Правый клик на компонент → **Save As Mesh**
2. Выбери **STL** формат
3. Настройки: High refinement

### Рекомендации для печати

- **Материал:** PETG или PLA+
- **Слой:** 0.2mm
- **Заполнение:** 20-30%
- **Стенки:** 3 периметра
- **Поддержки:** нужны для сервокреплений

## Провода и разъёмы

Не забудь про отверстия для:
- 2x FFC кабеля камер (15-pin)
- 4x провода микрофонов (I2S)
- Провод динамика
- USB/питание ESP32

## Доработка

Скрипт создаёт базовую геометрию. После генерации можешь:
- Добавить вентиляционные отверстия
- Добавить решётку динамика
- Скруглить углы (Fillet)
- Добавить крепёжные отверстия для сборки

## Troubleshooting

**Скрипт не запускается:**
- Проверь что Fusion в режиме Design (не Drawing/CAM)
- Попробуй создать новый пустой документ перед запуском

**Ошибка "Failed":**
- Посмотри детали в окне Text Commands (`View → Text Commands`)
- Обычно это проблема с геометрией - попробуй изменить параметры
